### ISSUE TITLE
crash when doubleclick to enter world

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/CherishedWorlds#1]
#### Notice
Please reproduce all issues without any other unnecessary mods before submitting.

#### Versions (Be specific, do not write "latest"):
* Cherished Worlds: 1.14.4-2.0-beta2.jar
* Forge: 28.0.93

#### Observed Behavior:
Tried entering my world with this mod, double clicked world. Crashed.
#### Expected Behavior:
Entering the world as normal, with double click as i always do.
#### Steps to Reproduce:
1. Start game with mod.
2. Try entering a world for me with double click
3. Crash.
...

Crash Log: Please use a paste site like [paste.ee](https://paste.ee/p/MgXMK).

**Comment by TheIllusiveC4** [comment]
Can you provide the crash log?

**Comment by TheIllusiveC4** [comment]
Weird, can't see why this is happening. I can't reproduce it on my end either. Do you have any other mods installed that change the menu? Can you try and repeat this without any other mods?
