### ISSUE TITLE
[Bug]: The displayed list of worlds is inconsistent with what you load

### ISSUE THREAD

**Issue by Boobies** [TheIllusiveC4/CherishedWorlds#12]
### Minecraft Version

1.17.1

### What happened?

First of all, there's no category for version 1.18 so I just selected 1.17.1. I believe this bug to be a regression although I have not tested any of the 1.17 builds (if there were any) in months.

So the bug happens is that if you have a cherished world, it will be displayed at the top of the list. However, the list of worlds behaves as if nothing were cherished when trying to load. So, essentially, you load the wrong world. I believe this is what is going on.

### How do you trigger this bug?

Had a cherished world, imported a couple of others, tried to load one of the new ones and it ended up loading the wrong thing. The bug can be reproduced reliably.

### Loader

Fabric

### Loader Version

0.12.12

### Fabric API Version

0.44.0

### Mod Version

2.0.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue. Attempting to load a favorited world loads the correct world in my testing.

> imported a couple of others

How did you import them? Did you rename any of them in the process?

In addition, if you reset the favorites list by deleting the `cherishedworlds` folder in the `configs` folder and then re-add the chosen worlds to your favorites, does this issue still occur?
