### ISSUE TITLE
[Feature]: Can you add a feature that lets you block worlds from serverside mods. Like a survival world that you do not want a serverside mod touching.

### ISSUE THREAD

**Issue by googlescientificnameforapig** [TheIllusiveC4/CherishedWorlds#13]
### What is the new feature or improvement?

plz?

**Comment by Aizistral** [comment]
I... think that goes a little beyound the scope of what this mod was designed to accomplish. That's not to say that the feature itself is bad, it's just not something you would expect to find as a part of Cherished Worlds in its current state.

**Comment by TheIllusiveC4** [comment]
Yeah, this isn't really within the scope of the mod. Even if it were, the logistics of such a feature seem somewhat problematic and not really something I'm interested in unfortunately.
