### ISSUE TITLE
[Bug]: minecraft 1.19 crashed when selecting Singleplayer option

### ISSUE THREAD

**Issue by Crykenpie** [TheIllusiveC4/CherishedWorlds#16]
### Minecraft Version

1.19.2

### What happened?

I expected the game to let me select the singleplayer option and look at my worlds to load and play one, then it crashes before letting me even see the worlds.  The world is 1.19 but that wasnt an option in minecraft version.

### How do you trigger this bug?

1. load up game
2.select singleplayer to choose a world
3. game says "saving world" before i can even see the worlds screen, then crashes
...

### Loader

Fabric

### Loader Version

Fabric 0.14.9

### Fabric API Version

Fabric API 0.58.0

### Mod Version

cherishedworlds-fabric-6.0.0+1.19.1

### Relevant Log Outputs

https://pastebin.com/gWp3rbEq

**Comment by TheIllusiveC4** [comment]
Since you are using a version of the mod built for 1.19.1, please downgrade to the latest version for 1.19 which is 6.0.0-beta.2+1.19 and see if that resolves your issue. Unfortunately, even if that doesn't fix your issue, 1.19 and 1.19.1 are no longer supported and will not receive any bug fixes.
