### ISSUE TITLE
[Bug]: Game crash

### ISSUE THREAD

**Issue by Modog500000** [TheIllusiveC4/CherishedWorlds#20]
### Minecraft Version

1.19.4

### What happened?

The game crashed by clicking on the screen
I Expect the game to not crash.

If you have more questions please contact me on discord
@ModogTheDev#4346

### How do you trigger this bug?

1.Opened the game on 1.19.4
2.Opened multiplayer
3.Clicked on the cherish world button
...

### Loader

Fabric

### Loader Version

Fabric - 0.14.19

### API Version

 fabric-api-0.77.0

### Mod Version

cherishedworlds-fabric-6.0.4

### Relevant Log Outputs

[https://pastebin.com/PQRX037n]((https://pastebin.com/PQRX037n))

**Comment by TheIllusiveC4** [comment]
This error actually seems to be from some mod called Iceberg? Does that seem familiar?

**Comment by Modog500000** [comment]
Yeah, its a dependency. Sorry for waiting your time. Kind of weird that it only triggers when I click on a cherished world button but its not your fault. The mod wasn't  updated.
