### ISSUE TITLE
[Bug]: Crash when moving added servers up and down in Multiplayer list.

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/CherishedWorlds#25]
### Minecraft Version

1.20.1

### What happened?

Crash when moving added servers up and down in Multiplayer list.

### How do you trigger this bug?

1. Add two servers.
2. Move both up and down.
3. Game crash.
Profit.

### Loader

Forge

### Loader Version

47.1.3

### API Version

N/A

### Mod Version

6.1.2

### Relevant Log Outputs

https://gist.githubusercontent.com/Gbergz/d9a53dc611d9846a2e9a9d6587f509e0/raw/1cc5ce24b9ee686c041afefe7f3cc94697e82319/gistfile1.txt

**Comment by TheIllusiveC4** [comment]
I can't reproduce this with just the instructions provided. I added two servers and moved them up and down without any crash. Can you provide more detailed steps? In addition, can you verify if this issue occurs with _only_ Cherished Worlds installed?

**Comment by Gbergz** [comment]
Didn't try with just Cherished World, my bad for not typing that, but it's reproducable in the modpack Limitless 7.

**Comment by TheIllusiveC4** [comment]
Luckily the first two candidates I saw in the logs had a hit, this is apparently an incompatibility with the BisectHosting Server Integration Menu mod. I'm not sure why yet though. If it's a valid option for you, removing that mod should provide a workaround for the moment.

**Comment by Gbergz** [comment]
With the latest update published(v6.1.3), the game crashes to desktop upon boot.

Logs: https://gist.githubusercontent.com/Gbergz/fed64c3a8f9512f137e70a9f532bf11e/raw/e64994a3b4e79a168a43f943bf4ba6f67a0306b8/gistfile1.txt
