### ISSUE TITLE
[Bug]: Cherished worlds and/or vice versa seems tae have problems when they both exist together.

### ISSUE THREAD

**Issue by SireAwfulThe1st** [TheIllusiveC4/CherishedWorlds#28]
### Minecraft Version

1.20.1

### What happened?

A crash everytime configured is on the same pack as Cherished's

### How do you trigger this bug?

1. Seems to happen when using MrCrayfish's Configured mod either during start up or whenever trying to access the ingame config menu that configuration has.

### Loader

Forge

### Loader Version

Forge - 47.2.17

### Mod Version

Cherished Worlds 6.1.4+1.20.1

### Relevant Log Outputs

[crash-2024-02-14_01.11.47-client.txt](https://github.com/illusivesoulworks/cherishedworlds/files/14280992/crash-2024-02-14_01.11.47-client.txt)
[crash-2024-02-14_01.13.40-client.txt](https://github.com/illusivesoulworks/cherishedworlds/files/14280993/crash-2024-02-14_01.13.40-client.txt)

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this with just Cherished Worlds and Configured, with only those installed there is no crash. If you cannot reproduce this with just those two mods, it's likely to be a conflict with a third unidentified mod. Also, the crash seems to be coming from Configured and not Cherished Worlds so, once that third mod is identified, you may need to report it to Configured instead.

**Comment by SireAwfulThe1st** [comment]
> I cannot reproduce this with just Cherished Worlds and Configured, with only those installed there is no crash. If you cannot reproduce this with just those two mods, it's likely to be a conflict with a third unidentified mod. Also, the crash seems to be coming from Configured and not Cherished Worlds so, once that third mod is identified, you may need to report it to Configured instead.

Got it, I'll investigate this now and maybe ask MrCrayfish, thanks for the help!
