### ISSUE TITLE
[Bug]: Visual issues with post-rewrite FancyMenu

### ISSUE THREAD

**Issue by lumiscosity** [TheIllusiveC4/CherishedWorlds#29]
### Minecraft Version

1.20.1

### What happened?

As of the recently released FancyMenu rewrite (v3), the world favourite icons are drawn over FancyMenu's configuration menus.
![image](https://github.com/illusivesoulworks/cherishedworlds/assets/26834471/2f745566-0e99-4594-be14-f3997014154c)

### How do you trigger this bug?

1. Install FancyMenu and Cherished Worlds.
2. Ensure that there are singleplayer worlds.
3. Open any dropdown menu provided by FancyMenu.
4. Note the layering issues.

### Loader

Fabric

### Loader Version

Fabric 0.15.7

### API Version

Fabric API 0.92.0

### Mod Version

6.1.5+1.20.1

**Comment by TheIllusiveC4** [comment]
The solution I ended up implementing just stops the rendering of the star icons when navigating the FancyMenu menus. Not ideal, but works well enough until I can figure out if it's possible to render the icons underneath the menus.
