### ISSUE TITLE
[Bug]: 1.20.1 Render thread/ERROR

### ISSUE THREAD

**Issue by Krimatoria** [TheIllusiveC4/CherishedWorlds#31]
### Minecraft Version

1.20.1

### What happened?

> [12:51:08] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Исключение, пойманное во время запуска события: de/keksuccino/fancymenu/customization/overlay/CustomizationOverlay Индекс: 23 Слушатели: 0: HIGH 1: ASM: class dev.architectury.event.forge.EventHandlerImplClient eventDrawScreenEvent(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 2: NORMAL 3: ASM: class com.aetherteam.cumulus.client.event.listeners.MenuListener onGuiDraw(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 4: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@129b1b51 5: ASM: class de.keksuccino.konkrete.gui.screens.popup.PopupHandler onRender(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 6: ASM: de.keksuccino.fancymenu.menu.fancy.MenuCustomizationEvents@4330d00c onRenderScreenPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 7: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MainMenuHandler@1afc0990 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 8: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MoreRefinedStorageMainHandler@7244c433 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 9: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.DummyCoreMainHandler@21a38af3 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 10: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.WorldLoadingScreenHandler@3c2023db onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 11: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.PauseScreenHandler@6470dc06 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 12: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@7015f2af 13: ASM: класс net.fabricmc.fabric.impl.client.screen.ScreenEventHooks afterScreenDraw(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 14: ASM: de.keksuccino.drippyloadingscreen.EventHandler@5009282f onDrawScreenPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 15: ASM: class io.github.lightman314.lightmanscurrency.client.ClientEvents renderInventoryTooltips(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 16: ASM: class com.aetherteam.aether.client.event.listeners.GuiListener onGuiDraw(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 17: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@2d55b075 18: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@26bb0894 19: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@6cb0ce81 20: ASM: de.keksuccino.drippyloadingscreen.customization.DrippyOverlayMenuHandler@23a4b714 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 21: ASM: dev.shadowsoffire.apotheosis.ench.EnchModuleClient@33c16e9c drawAnvilCostBlob(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 22: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@33efd932 23: ASM: com.illusivesoulworks.cherishedworlds.client.ScreenEventsListener@25c8525a onGuiDrawScreen(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 24: ASM: com.illusivesoulworks.polymorph.client.ClientEventsListener@439bf00f render(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 25: ASM: com.mrcrayfish.framework.client.ClientForgeEvents@38ae02b0 onScreenRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 26: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@33b91122 27: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@4d385069 28: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase@638106b7 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 29: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase@7f63db5b onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 30: ASM: de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase@4f08d81b onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 31: net.minecraftforge.eventbus.EventBus$$Lambda$1990/0x0000018f2a8bd000@27964b89 32: ASM: com.github.alexthe666.citadel.ClientProxy@43026a8b screenRender(Lnet/minecraftforge/client/event/ScreenEvent$Render;)V 33: НИЗКИЙ 34: ASM: de.keksuccino.fancymenu.menu.fancy.helper.CustomizationHelper@7d3af1f3 onRenderPost(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 35: НИЗКИЙ 36: ASM: de.keksuccino.konkrete.gui.content.AdvancedButtonHandler@7777592f onDrawScreen(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V 37: ASM: de.keksuccino.fancymenu.menu.button.VanillaButtonDescriptionHandler@44f9de48 onDrawScreen(Lnet/minecraftforge/client/event/ScreenEvent$Render$Post;)V java.lang.NoClassDefFoundError: de/keksuccino/fancymenu/customization/overlay/CustomizationOverlay в TRANSFORMER/cherishedworlds@6.1.6+1.20.1/com.illusivesoulworks.cherishedworlds.integration.FancyMenuIntegration.isNavigating(FancyMenuIntegration.java:9) в TRANSFORMER/cherishedworlds@6.1.6+1.20.1/com.illusivesoulworks.cherishedworlds.platform.ForgePlatformHelper.canRender(ForgePlatformHelper.java:51) в TRANSFORMER/cherishedworlds@6.1.6+1.20.1/com.illusivesoulworks.cherishedworlds.client.ScreenEvents.onDraw(ScreenEvents.java:35) в TRANSFORMER/cherishedworlds@6.1.6+1.20.1/com.illusivesoulworks.cherishedworlds.client.ScreenEventsListener.onGuiDrawScreen(ScreenEventsListener.java:27) в TRANSFORMER/cherishedworlds@6.1.6+1.20.1/com.illusivesoulworks.cherishedworlds.client.__ScreenEventsListener_onGuiDrawScreen_Post.invoke(.dynamic) в MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) в MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) в MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) в TRANSFORMER/forge@47.2.7/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:428) в TRANSFORMER/forge@47.2.7/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91362_(Minecraft.java:2141) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91320_(Minecraft.java:2110) в TRANSFORMER/notenoughcrashes@4.4.7+1.20.1/fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:54) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.handler$ffe000$notenoughcrashes$beforeCleanUpAfterCrash(Minecraft.java:22014) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91394_(Minecraft.java) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:736) в TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218) в java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(собственный метод) в java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(неизвестный источник) в java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(неизвестный источник) в java.base/java.lang.reflect.Method.invoke(Неизвестный источник) в MC-BOOTSTRAP/fmlloader@1.20.1-47.2.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) в MC-BOOTSTRAP/fmlloader@1.20.1-47.2.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) в MC-BOOTSTRAP/fmlloader@1.20.1-47.2.7/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) в MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) в cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) в java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(собственный метод) в java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(неизвестный источник) в java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(неизвестный источник) в java.base/java.lang.reflect.Method.invoke(неизвестный источник) в io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) в org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) в org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) в org.prismlauncher.EntryPoint.main(EntryPoint.java:70) Вызвано: java.lang.ClassNotFoundException: de.keksuccino.fancymenu.customization.overlay.CustomizationOverlay ... еще 42

### How do you trigger this bug?

cherishedworlds-forge-6.1.6+1.20.1.jar
fancymenu_forge_2.14.13_MC_1.20.1.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar

### Loader

Forge

### Loader Version

47.2.7

### Mod Version

cherishedworlds-forge-6.1.6+1.20.1.jar

**Comment by TheIllusiveC4** [comment]
> fancymenu_forge_2.14.13_MC_1.20.1.jar

You have an older version of Fancy Menu, this error should go away if you update to the latest version on 1.20.1.
