### ISSUE TITLE
[Feature]: Force the world icon to update on every load/disconnect

### ISSUE THREAD

**Issue by tajemniktv** [TheIllusiveC4/CherishedWorlds#35]
### What is the new feature or improvement?

Hey, was thinking it could be cool to have something like autoupdating icon for every (or every bookmarked world) in this mod, whatcha think?

**Comment by TheIllusiveC4** [comment]
While it would be a cool feature, I don't think it quite fits in with this mod specifically. It doesn't really have much to do with the core bookmarking feature.
