### ISSUE TITLE
[Bug]: Game Crashes whenever I click the multiplayer button

### ISSUE THREAD

**Issue by Parchoakes** [TheIllusiveC4/CherishedWorlds#36]
### Minecraft Version

1.20.1

### What happened?

My friend is trying to join me using essential and it is possible to join throught the multiplayer menu when to join however when they clicked multiplayer it would crash, and after removing cherished worlds it worked this could be a mod incompatibility or just a bug.

### How do you trigger this bug?

1. Open minecraft
2. Click multiplayer
3. It crashes

### Loader

Fabric

### Loader Version

Fabric - 0.16.9/0.16.5

### API Version

Fabric API 0.92.2+1.20.1

### Mod Version

cherishedworlds-fabric-6.1.6+1.20.1

### Relevant Log Outputs

[https://pastebin.com/UbaNxkP9](url)

**Comment by WimpieRatte** [comment]
Also getting this issue on Forge.

**Comment by Parchoakes** [comment]
> Also getting this issue on Forge.

After reading through other issues a bit more it's an incompatibility with essential.

**Comment by WimpieRatte** [comment]
Thanks!
Checking this now.

**Comment by WimpieRatte** [comment]
Looks like it's because Essential has it's own favourites section in Multiplayer now.

**Comment by TheIllusiveC4** [comment]
There's a fix for this on 1.21.1, I just need to backport it to 1.20.1.

**Comment by 7yudinglaopin8** [comment]
me too

**Comment by 7yudinglaopin8** [comment]
But I use forge(with connector).

**Comment by Parchoakes** [comment]
> I use forge(with connector). 

Are you also using essential? If so that probably the issue

**Comment by 7yudinglaopin8** [comment]
> > I use forge(with connector).
> 
> Are you also using essential? If so that probably the issue

Yes.

**Comment by TheIllusiveC4** [comment]
Very sorry for the delay on this. The new 6.1.7 update for 1.20.1 should address this issue.

**Comment by JustAPotota** [comment]
This still affects 1.20.4: https://mclo.gs/ixleYaG
