### ISSUE TITLE
[Feature]: 1.21.3 support

### ISSUE THREAD

**Issue by Ycoderdeez** [TheIllusiveC4/CherishedWorlds#37]
### What is the new feature or improvement?

please update to the newest version, or at least tell us if ur doing so.

**Comment by TheIllusiveC4** [comment]
With 1.21.4 coming out soon, a 1.21.3 port is no longer under consideration. And a port for 1.21.4 or above is yet undecided as I am currently focusing my development time on versions 1.21.1 and below.
